# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dde556a7e67c499f9a57f94243675b723ad1aed75a6caa20b6446bc10a2159dc967444b07cb5859f6b3d8e6bc1aa59bd16e706d8d50b107a59ab1b1b1e53117

test:
  secret_key_base: e6d51b7b2d0903bb43a147344107e84f13543440ab2af9eb6c8b94609fb6d81ccfc4e1d446e8c57256f61752d4dfc9375e33b99e2de13e3dbdc2fc0dd86b3078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
